import Tools1 from "/assets/tools/html.png";
import Tools2 from "/assets/tools/css.png";
import Tools3 from "/assets/tools/js.png";
import Tools4 from "/assets/tools/php.png";
import Tools5 from "/assets/tools/mysql.png";
import Tools6 from "/assets/tools/reactjs.png";
import Tools7 from "/assets/tools/tailwind.png";
import Tools8 from "/assets/tools/bootstrap.png";
import Tools9 from "/assets/tools/nodejs.png";
import Tools10 from "/assets/tools/github.png";
import Tools11 from "/assets/tools/vscode.png";
import Tools12 from "/assets/tools/firebase.png";
import Tools13 from "/assets/tools/vite.png";

export const listTools = [
  { id: 1, gambar: Tools1, nama: "HTML", ket: "Markup Language", dad: "100" },
  { id: 2, gambar: Tools2, nama: "CSS", ket: "Styling Language", dad: "200" },
  { id: 3, gambar: Tools3, nama: "JavaScript", ket: "Language", dad: "300" },
  { id: 4, gambar: Tools4, nama: "PHP", ket: "Language", dad: "400" },
  { id: 5, gambar: Tools5, nama: "MySQL", ket: "Database", dad: "500" },
  { id: 6, gambar: Tools6, nama: "React JS", ket: "Framework", dad: "600" },
  { id: 7, gambar: Tools7, nama: "Tailwind CSS", ket: "CSS Framework", dad: "700" },
  { id: 8, gambar: Tools8, nama: "Bootstrap", ket: "CSS Framework", dad: "800" },
  { id: 9, gambar: Tools9, nama: "Node JS", ket: "JavaScript Runtime", dad: "900" },
  { id: 10, gambar: Tools10, nama: "GitHub", ket: "Version Control", dad: "1000" },
  { id: 11, gambar: Tools11, nama: "VS Code", ket: "Code Editor", dad: "1100" },
  { id: 12, gambar: Tools12, nama: "Firebase", ket: "Backend Service", dad: "1200" },
  { id: 13, gambar: Tools13, nama: "Vite", ket: "Build Tool", dad: "1300" },
];

// type: "work" | "education" | "organization"
export const listExperience = [
  {
    id: 1,
    type: "work",
    period: "Des 2025 – Jun 2026",
    title: "Full Stack Developer",
    place: "Politeknik ATI Padang",
    badge: "Magang",
    desc: "Bertanggung jawab atas kegiatan teknologi informasi berbasis komputer, meliputi perencanaan, analisis, desain, implementasi, dan pengoperasian sistem informasi. Mengembangkan dan memelihara aplikasi web menggunakan Laravel dan Vue.js untuk front-end maupun back-end, termasuk pemeliharaan infrastruktur IT, troubleshooting, dan optimasi sistem.",
    delay: "0",
  },
  {
    id: 2,
    type: "work",
    period: "Feb – Mei 2025",
    title: "Full Stack Web Developer",
    place: "PT Media Sarana Data",
    badge: "Magang",
    desc: "Mengembangkan Sistem Pemesanan Janji temu berbasis web untuk mengatasi ketidakefisienan pemesanan manual di sektor klinik dan konsultasi. Dibangun menggunakan Laravel & Vue.js dengan RESTful API mengikuti Agile Scrum. Fitur: autentikasi, penjadwalan layanan, ulasan, integrasi Mapbox, verifikasi email, dan reset sandi berbasis OTP.",
    delay: "100",
  },
  {
    id: 3,
    type: "work",
    period: "Agt 2024 – Jan 2025",
    title: "Full Stack Web Developer",
    place: "PT Media Sarana Data",
    badge: "Magang",
    desc: "Mengembangkan sistem integrasi antara Sentry (platform pemantauan isu) dan OpenProject (sistem manajemen proyek) untuk mengotomatiskan transfer isu. Fitur meliputi dashboard statistik isu, manajemen proyek terintegrasi, dan halaman manajemen pengguna khusus admin.",
    delay: "200",
  },
  {
    id: 4,
    type: "work",
    period: "Feb – Jun 2024",
    title: "Mahasiswa Magang",
    place: "Dukcapil Kabupaten Sukoharjo",
    badge: "Magang",
    desc: "Mengembangkan sistem berbasis web untuk memfasilitasi pengumpulan data penduduk rentan dan memudahkan masyarakat melaporkan data secara cepat dan efisien. Menggantikan layanan sebelumnya yang ditinggalkan programmer lama dengan pendekatan yang lebih mudah diakses.",
    delay: "300",
  },
  {
    id: 5,
    type: "work",
    period: "Agt – Sep 2023",
    title: "Mobile App Developer",
    place: "UNS — Application Mobile Development",
    badge: "Proyek",
    desc: "Mengembangkan aplikasi mobile pemesanan tiket bioskop menggunakan Flutter dengan autentikasi Google. Pengguna dapat melihat film yang sedang tayang, mengakses detail film termasuk sinopsis dan rating, serta memilih kursi sesuai preferensi.",
    delay: "400",
  },
  {
    id: 6,
    type: "work",
    period: "Mei – Jun 2023",
    title: "Web Developer",
    place: "UNS — Web Development Project",
    badge: "Proyek",
    desc: "Membangun website rental mobil dengan arsitektur client-server untuk tiga jenis pengguna: penyewa, pemilik mobil, dan admin. Admin memiliki akses penuh untuk mengelola semua data, pemesanan, data pengguna, dan daftar mobil.",
    delay: "500",
  },
  {
    id: 7,
    type: "education",
    period: "Agt 2022 – Agt 2025",
    title: "Teknik Informatika",
    place: "Universitas Sebelas Maret (UNS) — Surakarta",
    badge: "IPK 3.80 / 4.00",
    desc: "Berfokus pada rekayasa perangkat lunak dan pengembangan web full stack. Membangun keahlian di bidang Laravel, Vue.js, React, dan berbagai teknologi web modern. Aktif dalam komunitas teknologi mahasiswa dan proyek pengembangan perangkat lunak.",
    delay: "600",
  },
  {
    id: 8,
    type: "organization",
    period: "Sep 2019 – Des 2021",
    title: "Ketua (Chairman) MPK",
    place: "MPK — Bukittinggi",
    badge: "Organisasi",
    desc: "Majelis Perwakilan Kelas adalah organisasi resmi untuk membantu kelancaran kegiatan komunitas sekolah. MPK berperan penting dalam memotivasi siswa agar aktif berpartisipasi dalam lingkungan sekolah.",
    delay: "700",
  },
  {
    id: 9,
    type: "organization",
    period: "Feb 2020 – Des 2021",
    title: "Sekbid Lingkungan Hidup",
    place: "KKR — Bukittinggi",
    badge: "Organisasi",
    desc: "Seksi Pemeliharaan Lingkungan bertugas menyusun, merencanakan, dan merancang program kegiatan pemeliharaan lingkungan untuk menjaga keseimbangan ekosistem dan meningkatkan kualitas lingkungan hidup.",
    delay: "800",
  },
];

// driveUrl: isi dengan link Google Drive dokumen sertifikat Anda
export const listCerts = [
  {
    id: 1,
    title: "Sertifikasi Programmer",
    issuer: "BSNP",
    year: "2025",
    icon: "ri-award-line",
    colorFrom: "#fbbf24",
    colorTo: "#f97316",
    driveUrl: null,
    delay: "0",
  },
  {
    id: 2,
    title: "DD Database Design Learner",
    issuer: "Oracle Academy",
    year: "2024",
    icon: "ri-database-2-line",
    colorFrom: "#ef4444",
    colorTo: "#b91c1c",
    driveUrl: null,
    delay: "100",
  },
  {
    id: 3,
    title: "Java Fundamentals",
    issuer: "Oracle Academy",
    year: "2023",
    icon: "ri-code-s-slash-line",
    colorFrom: "#f97316",
    colorTo: "#dc2626",
    driveUrl: null,
    delay: "200",
  },
  {
    id: 4,
    title: "DP Database Programming with SQL",
    issuer: "Oracle Academy",
    year: "2024",
    icon: "ri-database-line",
    colorFrom: "#ef4444",
    colorTo: "#b91c1c",
    driveUrl: null,
    delay: "300",
  },
  {
    id: 5,
    title: "Introduction to IoT & CCNA RS",
    issuer: "Cisco",
    year: "2023",
    icon: "ri-wifi-line",
    colorFrom: "#3b82f6",
    colorTo: "#1d4ed8",
    driveUrl: null,
    delay: "400",
  },
  {
    id: 6,
    title: "Red Hat System Administration II (RH134)",
    issuer: "Red Hat",
    year: "2023",
    icon: "ri-server-line",
    colorFrom: "#dc2626",
    colorTo: "#991b1b",
    driveUrl: null,
    delay: "500",
  },
  {
    id: 7,
    title: "SQL",
    issuer: "Sololearn",
    year: "2023",
    icon: "ri-terminal-box-line",
    colorFrom: "#06b6d4",
    colorTo: "#0891b2",
    driveUrl: null,
    delay: "600",
  },
  {
    id: 8,
    title: "Red Hat System Administration I (RH124)",
    issuer: "Red Hat",
    year: "2023",
    icon: "ri-server-line",
    colorFrom: "#dc2626",
    colorTo: "#991b1b",
    driveUrl: null,
    delay: "700",
  },
  {
    id: 9,
    title: "Red Hat OpenStack Administration I (CL110)",
    issuer: "Red Hat",
    year: "2023",
    icon: "ri-cloud-line",
    colorFrom: "#7c3aed",
    colorTo: "#6d28d9",
    driveUrl: null,
    delay: "800",
  },
];

import Proyek1 from "/assets/proyek/proyek1.jpg";
import Proyek2 from "/assets/proyek/proyek2.jpg";
import Proyek3 from "/assets/proyek/proyek3.jpg";
import Proyek4 from "/assets/proyek/proyek4.jpg";
import Proyek5 from "/assets/proyek/proyek5.jpg";
import Proyek6 from "/assets/proyek/proyek6.jpg";

export const listProyek = [
  {
    id: 1,
    image: Proyek1,
    title: "Booking Appointment System",
    subtitle: "Sistem pemesanan janji temu berbasis web dengan Laravel & Vue.js...",
    fullDescription: "Sistem dikembangkan untuk mengatasi ketidakefisienan pemesanan layanan manual di sektor klinik dan konsultasi, menawarkan solusi berbasis web yang lebih cepat dan akurat. Dibangun menggunakan Laravel dan Vue.js dengan RESTful API mengikuti framework Agile Scrum. Fitur utama: autentikasi pengguna, penjadwalan layanan, ulasan, dan integrasi Mapbox. Mendukung verifikasi email, reset sandi berbasis OTP, pelacakan status pemesanan, dan peta lokasi pertemuan. Pengujian menunjukkan keberhasilan 100% di delapan skenario utama.",
    techStack: ["Laravel", "Vue.js", "MySQL", "RESTful API", "Mapbox", "Tailwind CSS"],
    category: "Web App",
    duration: "Feb – Mei 2025",
    client: "PT Media Sarana Data",
    borderColor: "#3B82F6",
    gradient: "linear-gradient(145deg, #3B82F6, #000)",
    url: "https://github.com/raihanzaki03",
    dad: "100",
  },
  {
    id: 2,
    image: Proyek2,
    title: "Sentry & OpenProject Integration",
    subtitle: "Sistem integrasi Sentry dan OpenProject untuk otomatisasi manajemen isu...",
    fullDescription: "Mengembangkan sistem integrasi antara Sentry (platform pemantauan isu) dan OpenProject (sistem manajemen proyek) untuk mengotomatiskan proses transfer isu dan meningkatkan efisiensi manajemen tugas. Sistem dirancang untuk mengatasi keterbatasan proses manual yang rawan kesalahan, dengan fitur: autentikasi pengguna, dashboard statistik isu, manajemen proyek, dan manajemen isu terintegrasi. Terdapat halaman manajemen pengguna yang hanya dapat diakses admin untuk menambah, mengedit, menghapus, dan mengubah kata sandi pengguna.",
    techStack: ["Vue.js", "Laravel", "Sentry API", "OpenProject API", "MySQL", "Bootstrap"],
    category: "Integration",
    duration: "Agt 2024 – Jan 2025",
    client: "PT Media Sarana Data",
    borderColor: "#10B981",
    gradient: "linear-gradient(180deg, #10B981, #000)",
    url: "https://github.com/raihanzaki03",
    dad: "200",
  },
  {
    id: 3,
    image: Proyek3,
    title: "Sistem Pendataan Penduduk Rentan",
    subtitle: "Sistem web untuk pendataan penduduk rentan bagi Disdukcapil Sukoharjo...",
    fullDescription: "Mengembangkan sistem berbasis web untuk memfasilitasi pengumpulan data penduduk rentan dan memudahkan masyarakat melaporkan data secara cepat dan efisien. Sistem ini menggantikan layanan sebelumnya yang tidak lagi dapat diakses akibat ditinggalkan programmer sebelumnya. Dengan pendekatan yang lebih ramah pengguna, sistem menyediakan fitur pengumpulan data yang akurat, layanan pelaporan sederhana, dan akses mudah bagi masyarakat serta Disdukcapil Sukoharjo untuk memastikan layanan yang adil dan efektif bagi seluruh lapisan masyarakat.",
    techStack: ["Laravel", "MySQL", "Bootstrap", "PHP", "JavaScript"],
    category: "Web App",
    duration: "Feb – Jun 2024",
    client: "Dukcapil Kab. Sukoharjo",
    borderColor: "#3B82F6",
    gradient: "linear-gradient(145deg, #3B82F6, #000)",
    url: "https://github.com/raihanzaki03",
    dad: "300",
  },
  {
    id: 4,
    image: Proyek4,
    title: "Full Stack Web App — ATI Padang",
    subtitle: "Pengembangan dan pemeliharaan aplikasi web sebagai Full Stack Developer...",
    fullDescription: "Bertanggung jawab atas kegiatan teknologi informasi berbasis komputer, meliputi perencanaan, analisis, desain, implementasi, pengembangan, dan pengoperasian sistem informasi sebagai Full Stack Developer. Berpengalaman mengembangkan dan memelihara aplikasi web menggunakan teknologi modern seperti Laravel dan Vue.js, mencakup front-end maupun back-end. Tanggung jawab juga meliputi pengelolaan infrastruktur IT, sistem informasi, dan sistem multimedia, termasuk pemeliharaan, troubleshooting, optimasi, dan dukungan teknis untuk memastikan kinerja sistem yang efisien.",
    techStack: ["Laravel", "Vue.js", "MySQL", "Tailwind CSS", "PHP", "JavaScript"],
    category: "Full Stack",
    duration: "Des 2025 – Jun 2026",
    client: "Politeknik ATI Padang",
    borderColor: "#10B981",
    gradient: "linear-gradient(180deg, #10B981, #000)",
    url: "https://github.com/raihanzaki03",
    dad: "400",
  },
  {
    id: 5,
    image: Proyek5,
    title: "Website Rental Mobil",
    subtitle: "Website rental mobil dengan arsitektur client-server dan tiga jenis pengguna...",
    fullDescription: "Membangun website rental mobil menggunakan arsitektur client-server dengan tiga jenis pengguna: penyewa, pemilik mobil, dan admin. Penyewa dapat melihat detail mobil, melakukan pemesanan, dan membatalkan pesanan. Pemilik mobil dapat mengelola profil serta menambah atau mengedit daftar mobil yang disewakan. Admin memiliki akses penuh untuk mengelola semua data dan aktivitas di website, termasuk pemesanan, data pengguna, dan daftar mobil. Sistem dirancang untuk memberikan pengalaman yang mudah, efisien, dan terintegrasi bagi semua pihak yang terlibat.",
    techStack: ["PHP", "MySQL", "Bootstrap", "JavaScript", "CSS"],
    category: "Web App",
    duration: "Mei – Jun 2023",
    client: "UNS — Web Development Project",
    borderColor: "#3B82F6",
    gradient: "linear-gradient(145deg, #3B82F6, #000)",
    url: "https://github.com/raihanzaki03",
    dad: "500",
  },
  {
    id: 6,
    image: Proyek6,
    title: "Aplikasi Pemesanan Tiket Bioskop",
    subtitle: "Aplikasi mobile pemesanan tiket bioskop dengan Flutter dan Firebase...",
    fullDescription: "Mengembangkan aplikasi mobile pemesanan tiket bioskop menggunakan framework Flutter, dirancang untuk memberikan pengalaman pengguna yang mudah dan modern. Aplikasi memungkinkan pengguna login dan registrasi melalui integrasi akun Google. Pembeli dapat melihat daftar film yang sedang tayang, mengakses detail film termasuk sinopsis dan rating, serta memilih kursi sesuai preferensi. Dengan antarmuka yang intuitif dan fitur-fitur fungsional, aplikasi memudahkan proses pemesanan tiket bioskop secara praktis dan efisien.",
    techStack: ["Flutter", "Dart", "Firebase", "Google Auth"],
    category: "Mobile App",
    duration: "Agt – Sep 2023",
    client: "UNS — Application Mobile Development",
    borderColor: "#10B981",
    gradient: "linear-gradient(180deg, #10B981, #000)",
    url: "https://github.com/raihanzaki03",
    dad: "600",
  },
];
